name: Gestore Library
on: [push]

jobs:
  test:
    name: Python ${{ matrix.python-version }} - Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 2.7
          - django-version: 1.11

          - python-version: 3.5
            django-version: 2.2

          - python-version: 3.8
            django-version: 2.2
          - python-version: 3.8
            django-version: 3.1
          - python-version: 3.8
            django-version: 3.2

          - python-version: 3.9
            django-version: 2.2
          - python-version: 3.9
            django-version: 3.1
          - python-version: 3.9
            django-version: 3.2
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          django-version: ${{ matrix.django-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 tox semantic-version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Test library version
        run: python -c "from gestore import __version__; from semantic_version import Version; Version(__version__)"
      - name: Lint with flake8
        run: flake8 gestore demoapp --statistics
      - name: Test with tox
        run: |
          runenv=$(echo "${{ matrix.python-version }}" | sed 's/\([2-3]\)\.\([0-9]\)/py\1\2/')
          djangoenv=$(echo "${{ matrix.django-version }}" | sed 's/\([2-3]\)\.\([0-9]\)/django\1\2/')
          tox -e $runenv-$djangoenv
